name = "Simulation"
authors = ["Chaitanya Kumar <chaitanyak28771@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
